// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/fast_html2md_functions.dart';
import 'api/monolith_functions.dart';
import 'api/pdf_text_extractor.dart';
import 'api/rustpotion.dart';
import 'api/simple.dart';
import 'api/text_splitter.dart';
import 'api/tokenizer.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => 278893951;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_offline_engine',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  bool crateApiMonolithFunctionsDownloadWebPage({required String url});

  TokenizerOutput crateApiTokenizerEncodeText({required String input});

  List<TextWithLocation> crateApiPdfTextExtractorExtractTextFromPdf(
      {required List<int> pdfBytes});

  List<TextWithLocation> crateApiPdfTextExtractorExtractTextFromPdfExtract(
      {required List<int> pdfBytes});

  List<TextWithLocation>
      crateApiPdfTextExtractorExtractTextFromPdfExtractMultithreaded(
          {required List<int> pdfBytes});

  Float64List crateApiRustpotionGetEmbeddingFromRustpotion(
      {required String text});

  List<Float64List> crateApiRustpotionGetEmbeddingsFromRustpotion(
      {required List<String> texts});

  String crateApiSimpleGreet({required String name});

  String crateApiFastHtml2MdFunctionsHtmlToMarkdown(
      {required String htmlContent, required String outputPath});

  String crateApiFastHtml2MdFunctionsHtmlToText(
      {required String htmlContent,
      required String outputPath,
      required BigInt width});

  String crateApiFastHtml2MdFunctionsHtmlToTextReadability(
      {required String htmlContent,
      required String outputPath,
      required BigInt width});

  String crateApiFastHtml2MdFunctionsHtmlToTextRich(
      {required String htmlContent,
      required String outputPath,
      required BigInt width});

  Future<void> crateApiSimpleInitApp();

  bool crateApiRustpotionInitPotion({required String appDir});

  bool crateApiTokenizerInitTokenizer({required String tokenizerPath});

  List<String> crateApiTextSplitterSemanticChunking(
      {required String text, required int maxChars});

  List<String> crateApiTextSplitterSemanticChunkingV2(
      {required String text, required int minChunkSize});

  List<String> crateApiTextSplitterSplitText(
      {required String text, required int maxChars});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  bool crateApiMonolithFunctionsDownloadWebPage({required String url}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(url, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 1)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiMonolithFunctionsDownloadWebPageConstMeta,
      argValues: [url],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiMonolithFunctionsDownloadWebPageConstMeta =>
      const TaskConstMeta(
        debugName: "download_web_page",
        argNames: ["url"],
      );

  @override
  TokenizerOutput crateApiTokenizerEncodeText({required String input}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(input, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 2)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_tokenizer_output,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTokenizerEncodeTextConstMeta,
      argValues: [input],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTokenizerEncodeTextConstMeta =>
      const TaskConstMeta(
        debugName: "encode_text",
        argNames: ["input"],
      );

  @override
  List<TextWithLocation> crateApiPdfTextExtractorExtractTextFromPdf(
      {required List<int> pdfBytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(pdfBytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 3)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_text_with_location,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPdfTextExtractorExtractTextFromPdfConstMeta,
      argValues: [pdfBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiPdfTextExtractorExtractTextFromPdfConstMeta =>
      const TaskConstMeta(
        debugName: "extract_text_from_pdf",
        argNames: ["pdfBytes"],
      );

  @override
  List<TextWithLocation> crateApiPdfTextExtractorExtractTextFromPdfExtract(
      {required List<int> pdfBytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(pdfBytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 4)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_text_with_location,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiPdfTextExtractorExtractTextFromPdfExtractConstMeta,
      argValues: [pdfBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiPdfTextExtractorExtractTextFromPdfExtractConstMeta =>
          const TaskConstMeta(
            debugName: "extract_text_from_pdf_extract",
            argNames: ["pdfBytes"],
          );

  @override
  List<TextWithLocation>
      crateApiPdfTextExtractorExtractTextFromPdfExtractMultithreaded(
          {required List<int> pdfBytes}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_prim_u_8_loose(pdfBytes, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 5)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_text_with_location,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta:
          kCrateApiPdfTextExtractorExtractTextFromPdfExtractMultithreadedConstMeta,
      argValues: [pdfBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiPdfTextExtractorExtractTextFromPdfExtractMultithreadedConstMeta =>
          const TaskConstMeta(
            debugName: "extract_text_from_pdf_extract_multithreaded",
            argNames: ["pdfBytes"],
          );

  @override
  Float64List crateApiRustpotionGetEmbeddingFromRustpotion(
      {required String text}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 6)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_prim_f_64_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRustpotionGetEmbeddingFromRustpotionConstMeta,
      argValues: [text],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRustpotionGetEmbeddingFromRustpotionConstMeta =>
      const TaskConstMeta(
        debugName: "get_embedding_from_rustpotion",
        argNames: ["text"],
      );

  @override
  List<Float64List> crateApiRustpotionGetEmbeddingsFromRustpotion(
      {required List<String> texts}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(texts, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 7)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_list_prim_f_64_strict,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRustpotionGetEmbeddingsFromRustpotionConstMeta,
      argValues: [texts],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRustpotionGetEmbeddingsFromRustpotionConstMeta =>
      const TaskConstMeta(
        debugName: "get_embeddings_from_rustpotion",
        argNames: ["texts"],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(name, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 8)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  String crateApiFastHtml2MdFunctionsHtmlToMarkdown(
      {required String htmlContent, required String outputPath}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(htmlContent, serializer);
        sse_encode_String(outputPath, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 9)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFastHtml2MdFunctionsHtmlToMarkdownConstMeta,
      argValues: [htmlContent, outputPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFastHtml2MdFunctionsHtmlToMarkdownConstMeta =>
      const TaskConstMeta(
        debugName: "html_to_markdown",
        argNames: ["htmlContent", "outputPath"],
      );

  @override
  String crateApiFastHtml2MdFunctionsHtmlToText(
      {required String htmlContent,
      required String outputPath,
      required BigInt width}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(htmlContent, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_usize(width, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 10)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFastHtml2MdFunctionsHtmlToTextConstMeta,
      argValues: [htmlContent, outputPath, width],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFastHtml2MdFunctionsHtmlToTextConstMeta =>
      const TaskConstMeta(
        debugName: "html_to_text",
        argNames: ["htmlContent", "outputPath", "width"],
      );

  @override
  String crateApiFastHtml2MdFunctionsHtmlToTextReadability(
      {required String htmlContent,
      required String outputPath,
      required BigInt width}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(htmlContent, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_usize(width, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 11)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFastHtml2MdFunctionsHtmlToTextReadabilityConstMeta,
      argValues: [htmlContent, outputPath, width],
      apiImpl: this,
    ));
  }

  TaskConstMeta
      get kCrateApiFastHtml2MdFunctionsHtmlToTextReadabilityConstMeta =>
          const TaskConstMeta(
            debugName: "html_to_text_readability",
            argNames: ["htmlContent", "outputPath", "width"],
          );

  @override
  String crateApiFastHtml2MdFunctionsHtmlToTextRich(
      {required String htmlContent,
      required String outputPath,
      required BigInt width}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(htmlContent, serializer);
        sse_encode_String(outputPath, serializer);
        sse_encode_usize(width, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 12)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFastHtml2MdFunctionsHtmlToTextRichConstMeta,
      argValues: [htmlContent, outputPath, width],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFastHtml2MdFunctionsHtmlToTextRichConstMeta =>
      const TaskConstMeta(
        debugName: "html_to_text_rich",
        argNames: ["htmlContent", "outputPath", "width"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  bool crateApiRustpotionInitPotion({required String appDir}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(appDir, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 14)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiRustpotionInitPotionConstMeta,
      argValues: [appDir],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiRustpotionInitPotionConstMeta =>
      const TaskConstMeta(
        debugName: "init_potion",
        argNames: ["appDir"],
      );

  @override
  bool crateApiTokenizerInitTokenizer({required String tokenizerPath}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(tokenizerPath, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 15)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTokenizerInitTokenizerConstMeta,
      argValues: [tokenizerPath],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTokenizerInitTokenizerConstMeta =>
      const TaskConstMeta(
        debugName: "init_tokenizer",
        argNames: ["tokenizerPath"],
      );

  @override
  List<String> crateApiTextSplitterSemanticChunking(
      {required String text, required int maxChars}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        sse_encode_i_32(maxChars, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 16)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTextSplitterSemanticChunkingConstMeta,
      argValues: [text, maxChars],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTextSplitterSemanticChunkingConstMeta =>
      const TaskConstMeta(
        debugName: "semantic_chunking",
        argNames: ["text", "maxChars"],
      );

  @override
  List<String> crateApiTextSplitterSemanticChunkingV2(
      {required String text, required int minChunkSize}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        sse_encode_i_32(minChunkSize, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 17)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTextSplitterSemanticChunkingV2ConstMeta,
      argValues: [text, minChunkSize],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTextSplitterSemanticChunkingV2ConstMeta =>
      const TaskConstMeta(
        debugName: "semantic_chunking_v2",
        argNames: ["text", "minChunkSize"],
      );

  @override
  List<String> crateApiTextSplitterSplitText(
      {required String text, required int maxChars}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(text, serializer);
        sse_encode_i_32(maxChars, serializer);
        return pdeCallFfi(generalizedFrbRustBinding, serializer, funcId: 18)!;
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiTextSplitterSplitTextConstMeta,
      argValues: [text, maxChars],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiTextSplitterSplitTextConstMeta =>
      const TaskConstMeta(
        debugName: "split_text",
        argNames: ["text", "maxChars"],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  double dco_decode_f_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<Float64List> dco_decode_list_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>)
        .map(dco_decode_list_prim_f_64_strict)
        .toList();
  }

  @protected
  Float64List dco_decode_list_prim_f_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Float64List;
  }

  @protected
  Int64List dco_decode_list_prim_i_64_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeInt64List(raw);
  }

  @protected
  List<int> dco_decode_list_prim_u_8_loose(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as List<int>;
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<TextWithLocation> dco_decode_list_text_with_location(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_text_with_location).toList();
  }

  @protected
  TextWithLocation dco_decode_text_with_location(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return TextWithLocation(
      text: dco_decode_String(arr[0]),
      pageNumber: dco_decode_i_32(arr[1]),
    );
  }

  @protected
  TokenizerOutput dco_decode_tokenizer_output(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return TokenizerOutput(
      inputIds: dco_decode_list_prim_i_64_strict(arr[0]),
      tokenTypeIds: dco_decode_list_prim_i_64_strict(arr[1]),
      attentionMask: dco_decode_list_prim_i_64_strict(arr[2]),
    );
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  double sse_decode_f_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat64();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<Float64List> sse_decode_list_list_prim_f_64_strict(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <Float64List>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_list_prim_f_64_strict(deserializer));
    }
    return ans_;
  }

  @protected
  Float64List sse_decode_list_prim_f_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getFloat64List(len_);
  }

  @protected
  Int64List sse_decode_list_prim_i_64_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getInt64List(len_);
  }

  @protected
  List<int> sse_decode_list_prim_u_8_loose(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<TextWithLocation> sse_decode_list_text_with_location(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <TextWithLocation>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_text_with_location(deserializer));
    }
    return ans_;
  }

  @protected
  TextWithLocation sse_decode_text_with_location(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_text = sse_decode_String(deserializer);
    var var_pageNumber = sse_decode_i_32(deserializer);
    return TextWithLocation(text: var_text, pageNumber: var_pageNumber);
  }

  @protected
  TokenizerOutput sse_decode_tokenizer_output(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_inputIds = sse_decode_list_prim_i_64_strict(deserializer);
    var var_tokenTypeIds = sse_decode_list_prim_i_64_strict(deserializer);
    var var_attentionMask = sse_decode_list_prim_i_64_strict(deserializer);
    return TokenizerOutput(
        inputIds: var_inputIds,
        tokenTypeIds: var_tokenTypeIds,
        attentionMask: var_attentionMask);
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_f_64(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat64(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_list_prim_f_64_strict(
      List<Float64List> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_list_prim_f_64_strict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_f_64_strict(
      Float64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putFloat64List(self);
  }

  @protected
  void sse_encode_list_prim_i_64_strict(
      Int64List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putInt64List(self);
  }

  @protected
  void sse_encode_list_prim_u_8_loose(
      List<int> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer
        .putUint8List(self is Uint8List ? self : Uint8List.fromList(self));
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_text_with_location(
      List<TextWithLocation> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_text_with_location(item, serializer);
    }
  }

  @protected
  void sse_encode_text_with_location(
      TextWithLocation self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.text, serializer);
    sse_encode_i_32(self.pageNumber, serializer);
  }

  @protected
  void sse_encode_tokenizer_output(
      TokenizerOutput self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_i_64_strict(self.inputIds, serializer);
    sse_encode_list_prim_i_64_strict(self.tokenTypeIds, serializer);
    sse_encode_list_prim_i_64_strict(self.attentionMask, serializer);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
