// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'main.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 4964726669154631150),
      name: 'DocumentSection',
      lastPropertyId: const obx_int.IdUid(7, 2704757728934759722),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1183312628321483769),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6087028067984702727),
            name: 'content',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1264405584400599170),
            name: 'embedding',
            type: 28,
            flags: 8,
            indexId: const obx_int.IdUid(1, 2040346046367731954),
            hnswParams: obx_int.ModelHnswParams(
              dimensions: 500,
              neighborsPerNode: 16,
              indexingSearchCount: 50,
              distanceType: 2,
            )),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5451520023004907108),
            name: 'documentId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 8765925163213436365),
            relationTarget: 'Document'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 7092109920362569719),
            name: 'pageNumber',
            type: 5,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2704757728934759722),
            name: 'originalId',
            type: 5,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 4580258393220083479),
      name: 'Document',
      lastPropertyId: const obx_int.IdUid(6, 4563067927403698562),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2844047832620198574),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 2995196551746699685),
            name: 'filename',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 6732924085827320716),
            name: 'fileType',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 5401630156356434121),
            name: 'hash',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 4563067927403698562),
            name: 'base64Content',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(2, 4580258393220083479),
      lastIndexId: const obx_int.IdUid(2, 8765925163213436365),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [6314157246497554813, 4106318852517374738],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    DocumentSection: obx_int.EntityDefinition<DocumentSection>(
        model: _entities[0],
        toOneRelations: (DocumentSection object) => [object.document],
        toManyRelations: (DocumentSection object) => {},
        getId: (DocumentSection object) => object.id,
        setId: (DocumentSection object, int id) {
          object.id = id;
        },
        objectToFB: (DocumentSection object, fb.Builder fbb) {
          final contentOffset = fbb.writeString(object.content);
          final embeddingOffset = object.embedding == null
              ? null
              : fbb.writeListFloat32(object.embedding!);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(2, contentOffset);
          fbb.addOffset(3, embeddingOffset);
          fbb.addInt64(4, object.document.targetId);
          fbb.addInt32(5, object.pageNumber);
          fbb.addInt32(6, object.originalId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final contentParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final embeddingParam =
              const fb.ListReader<double>(fb.Float32Reader(), lazy: false)
                  .vTableGetNullable(buffer, rootOffset, 10);
          final pageNumberParam =
              const fb.Int32Reader().vTableGet(buffer, rootOffset, 14, 0);
          final object = DocumentSection(
              content: contentParam,
              embedding: embeddingParam,
              pageNumber: pageNumberParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..originalId =
                const fb.Int32Reader().vTableGet(buffer, rootOffset, 16, 0);
          object.document.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          object.document.attach(store);
          return object;
        }),
    Document: obx_int.EntityDefinition<Document>(
        model: _entities[1],
        toOneRelations: (Document object) => [],
        toManyRelations: (Document object) => {},
        getId: (Document object) => object.id,
        setId: (Document object, int id) {
          object.id = id;
        },
        objectToFB: (Document object, fb.Builder fbb) {
          final filenameOffset = fbb.writeString(object.filename);
          final fileTypeOffset = fbb.writeString(object.fileType);
          final hashOffset = fbb.writeString(object.hash);
          final base64ContentOffset = fbb.writeString(object.base64Content);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, filenameOffset);
          fbb.addOffset(3, fileTypeOffset);
          fbb.addOffset(4, hashOffset);
          fbb.addOffset(5, base64ContentOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final filenameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final base64ContentParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 14, '');
          final fileTypeParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final hashParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 12, '');
          final object = Document(
              filename: filenameParam,
              base64Content: base64ContentParam,
              fileType: fileTypeParam,
              hash: hashParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [DocumentSection] entity fields to define ObjectBox queries.
class DocumentSection_ {
  /// See [DocumentSection.id].
  static final id =
      obx.QueryIntegerProperty<DocumentSection>(_entities[0].properties[0]);

  /// See [DocumentSection.content].
  static final content =
      obx.QueryStringProperty<DocumentSection>(_entities[0].properties[1]);

  /// See [DocumentSection.embedding].
  static final embedding =
      obx.QueryHnswProperty<DocumentSection>(_entities[0].properties[2]);

  /// See [DocumentSection.document].
  static final document = obx.QueryRelationToOne<DocumentSection, Document>(
      _entities[0].properties[3]);

  /// See [DocumentSection.pageNumber].
  static final pageNumber =
      obx.QueryIntegerProperty<DocumentSection>(_entities[0].properties[4]);

  /// See [DocumentSection.originalId].
  static final originalId =
      obx.QueryIntegerProperty<DocumentSection>(_entities[0].properties[5]);
}

/// [Document] entity fields to define ObjectBox queries.
class Document_ {
  /// See [Document.id].
  static final id =
      obx.QueryIntegerProperty<Document>(_entities[1].properties[0]);

  /// See [Document.filename].
  static final filename =
      obx.QueryStringProperty<Document>(_entities[1].properties[1]);

  /// See [Document.fileType].
  static final fileType =
      obx.QueryStringProperty<Document>(_entities[1].properties[2]);

  /// See [Document.hash].
  static final hash =
      obx.QueryStringProperty<Document>(_entities[1].properties[3]);

  /// See [Document.base64Content].
  static final base64Content =
      obx.QueryStringProperty<Document>(_entities[1].properties[4]);
}
