// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `init_fast_embed`

Float64List getEmbeddingFromFastEmbed({required String text}) =>
    RustLib.instance.api.crateApiFastEmbedGetEmbeddingFromFastEmbed(text: text);

List<Float64List> getEmbeddingsFromFastEmbed({required List<String> texts}) =>
    RustLib.instance.api
        .crateApiFastEmbedGetEmbeddingsFromFastEmbed(texts: texts);
