// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `clean_text`

String htmlToMarkdown(
        {required String htmlContent, required String outputPath}) =>
    RustLib.instance.api.crateApiFastHtml2MdFunctionsHtmlToMarkdown(
        htmlContent: htmlContent, outputPath: outputPath);

String htmlToText(
        {required String htmlContent,
        required String outputPath,
        required BigInt width}) =>
    RustLib.instance.api.crateApiFastHtml2MdFunctionsHtmlToText(
        htmlContent: htmlContent, outputPath: outputPath, width: width);

String htmlToTextRich(
        {required String htmlContent,
        required String outputPath,
        required BigInt width}) =>
    RustLib.instance.api.crateApiFastHtml2MdFunctionsHtmlToTextRich(
        htmlContent: htmlContent, outputPath: outputPath, width: width);

String htmlToTextReadability(
        {required String htmlContent,
        required String outputPath,
        required BigInt width}) =>
    RustLib.instance.api.crateApiFastHtml2MdFunctionsHtmlToTextReadability(
        htmlContent: htmlContent, outputPath: outputPath, width: width);
