// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `mean_pooling`

bool initModel({required String modelPath}) =>
    RustLib.instance.api.crateApiOrtFunctionsInitModel(modelPath: modelPath);

bool testModelLoad({required String appDir}) =>
    RustLib.instance.api.crateApiOrtFunctionsTestModelLoad(appDir: appDir);

Float32List testModelInference({required String appDir}) =>
    RustLib.instance.api.crateApiOrtFunctionsTestModelInference(appDir: appDir);

Float32List ortTokenizeAndInfer({required String text}) =>
    RustLib.instance.api.crateApiOrtFunctionsOrtTokenizeAndInfer(text: text);

List<Float32List> ortTokenizeAndInferMany({required List<String> texts}) =>
    RustLib.instance.api
        .crateApiOrtFunctionsOrtTokenizeAndInferMany(texts: texts);
