// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_pdfium_path`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `fmt`

List<TextWithLocation> extractTextFromPdfExtract(
        {required List<int> pdfBytes}) =>
    RustLib.instance.api
        .crateApiPdfTextExtractorExtractTextFromPdfExtract(pdfBytes: pdfBytes);

List<TextWithLocation> extractTextFromPdf({required List<int> pdfBytes}) =>
    RustLib.instance.api
        .crateApiPdfTextExtractorExtractTextFromPdf(pdfBytes: pdfBytes);

List<TextWithLocation> extractTextFromPdfExtractMultithreaded(
        {required List<int> pdfBytes}) =>
    RustLib.instance.api
        .crateApiPdfTextExtractorExtractTextFromPdfExtractMultithreaded(
            pdfBytes: pdfBytes);

class TextWithLocation {
  final String text;
  final int pageNumber;

  const TextWithLocation({
    required this.text,
    required this.pageNumber,
  });

  @override
  int get hashCode => text.hashCode ^ pageNumber.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is TextWithLocation &&
          runtimeType == other.runtimeType &&
          text == other.text &&
          pageNumber == other.pageNumber;
}
