// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `get_inherited`

Future<String> extractTextByPage(
        {required Document doc, required int pageNum}) =>
    RustLib.instance.api
        .crateApiPdfExtractLocalExtractTextByPage(doc: doc, pageNum: pageNum);

Future<void> outputDocPage(
        {required Document doc,
        required OutputDev output,
        required int pageNum}) =>
    RustLib.instance.api.crateApiPdfExtractLocalOutputDocPage(
        doc: doc, output: output, pageNum: pageNum);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Document>>
abstract class Document implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<OutputError>>
abstract class OutputError implements RustOpaqueInterface {}

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<dyn OutputDev>>
abstract class OutputDev implements RustOpaqueInterface {}
