// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These types are ignored because they are not used by any `pub` functions: `PotionWrapper`

bool initPotion({required String appDir}) =>
    RustLib.instance.api.crateApiRustpotionInitPotion(appDir: appDir);

Float64List getEmbeddingFromRustpotion({required String text}) =>
    RustLib.instance.api
        .crateApiRustpotionGetEmbeddingFromRustpotion(text: text);

List<Float64List> getEmbeddingsFromRustpotion({required List<String> texts}) =>
    RustLib.instance.api
        .crateApiRustpotionGetEmbeddingsFromRustpotion(texts: texts);
