// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `cosine_similarity`

List<String> splitText({required String text, required int maxChars}) =>
    RustLib.instance.api
        .crateApiTextSplitterSplitText(text: text, maxChars: maxChars);

List<String> semanticChunking({required String text, required int maxChars}) =>
    RustLib.instance.api
        .crateApiTextSplitterSemanticChunking(text: text, maxChars: maxChars);

List<String> semanticChunkingV2(
        {required String text, required int minChunkSize}) =>
    RustLib.instance.api.crateApiTextSplitterSemanticChunkingV2(
        text: text, minChunkSize: minChunkSize);
