// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

Tokenizer getBertTokenizer() =>
    RustLib.instance.api.crateApiTokenizersGetBertTokenizer();

Int64List encodeText({required Tokenizer tokenizer, required String text}) =>
    RustLib.instance.api
        .crateApiTokenizersEncodeText(tokenizer: tokenizer, text: text);

// Rust type: RustOpaqueMoi<flutter_rust_bridge::for_generated::RustAutoOpaqueInner<Tokenizer>>
abstract class Tokenizer implements RustOpaqueInterface {}
